### ISSUE TITLE
Bug report : query count is incorrect.

### ISSUE THREAD

**Issue by machanic** [ash-aldujaili/blackbox-adv-examples-signhunter#4]
The query count is incorrect.
In https://github.com/ash-aldujaili/blackbox-adv-examples-signhunter/blob/master/src/attacks/blackbox/sign_attack.py#L57
It only shows the code of `add_queries = 3` in the initialization part.
But after that the `add_queries` does not change anymore. However, the code of `loss_fct(.)` would also consume queries, why don't count that query?
For example, in https://github.com/ash-aldujaili/blackbox-adv-examples-signhunter/blob/master/src/attacks/blackbox/sign_attack.py#L64

**Comment by ash-aldujaili** [comment]
Hi @machanic ,

Thank you for your interest and your post. Hope the below clarifies your doubt.

The `_suggest` method of the attacks (be it SignHunter, NES, etc) represents a single iteration of the attack. The number of queries used in each `_suggest` call can be different depending on the attack logic. The total number of queries made are returned by the method (https://github.com/ash-aldujaili/blackbox-adv-examples-signhunter/blob/master/src/attacks/blackbox/sign_attack.py#L82 second argument). The total number of queries made by the algortihm (over all iterations) are tracked in the piece of code calling `_suggest`  (e.g., https://github.com/ash-aldujaili/blackbox-adv-examples-signhunter/blob/master/src/attacks/blackbox/black_box_attack.py#L167).

In the specific example of `add_queries = 3`. This is tailored to `SignHunter`'s logic. As upon initialization (the first iteration of the attack), the method will consume/call loss_fct 4 times as indicated by `np.ones(_shape[0]) + add_queries` = 4. As the attack proceeds in the rest of iterations (future calls of `_suggest`), it will only consume one `loss_fct` per `_suggest` and so `np.ones(_shape[0]) + add_queries` = 1, since `add_queries = 0`.

Hope the above clarifies your doubt.

Thank you.

**Comment by machanic** [comment]
@ash-aldujaili Why the `the first iteration of the attack` consumes 4 times of `loss_fct` call? I think it should be 3. Because at https://github.com/ash-aldujaili/blackbox-adv-examples-signhunter/blob/master/src/attacks/blackbox/sign_attack.py#L55, you call `loss_fct(bxs_t.cpu().numpy())` and then in https://github.com/ash-aldujaili/blackbox-adv-examples-signhunter/blob/master/src/attacks/blackbox/sign_attack.py#L64, the result of `loss_fct(bxs_t.cpu().numpy())` can be reused without calling `loss_fct` because the input `bxs_t` is the same (`bxs_t = self.xo_t` ) between two calls.

**Comment by ash-aldujaili** [comment]
@machanic you're correct. I think I set it then to `3 + 1` at the time without re-use assumption. I could change this in the source code, but its effect is negligible. The current version is over-counting the number of queries by one.

Thank you for the remark.
